app:
    resource: '@AppBundle/Controller/'
    type: annotation
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }
app_question:
    resource: "@AppBundle/Resources/config/routing/question.yml"
    prefix:   /question
app_quiz:
    resource: "@AppBundle/Resources/config/routing/quiz.yml"
    prefix:   /quiz
