quiz_index:
    path:     /
    defaults: { _controller: "AppBundle:Quiz:index" }
    methods:  GET

quiz_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Quiz:show" }
    methods:  GET

quiz_new:
    path:     /new
    defaults: { _controller: "AppBundle:Quiz:new" }
    methods:  [GET, POST]

quiz_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Quiz:edit" }
    methods:  [GET, POST]

quiz_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Quiz:delete" }
    methods:  DELETE
